insert into provincia (nombre) values ('Buenos aires');
insert into provincia (nombre) values ('Catamarca');
insert into provincia (nombre) values ('Chaco');
insert into provincia (nombre) values ('Chubut');
insert into provincia (nombre) values ('Córdoba');
insert into provincia (nombre) values ('Corrientes');
insert into provincia (nombre) values ('Entre ríos');
insert into provincia (nombre) values ('Formosa');
insert into provincia (nombre) values ('Jujuy');
insert into provincia (nombre) values ('La Pampa');
insert into provincia (nombre) values ('La Rioja');
insert into provincia (nombre) values ('Mendoza');
insert into provincia (nombre) values ('Misiones');
insert into provincia (nombre) values ('Neuquén');
insert into provincia (nombre) values ('Río Negro');
insert into provincia (nombre) values ('Salta');
insert into provincia (nombre) values ('San Juan');
insert into provincia (nombre) values ('San Luis');
insert into provincia (nombre) values ('Santa Cruz');
insert into provincia (nombre) values ('Santa Fé');
insert into provincia (nombre) values ('Santiago del Estero');
insert into provincia (nombre) values ('Tierra del Fuego');
insert into provincia (nombre) values ('Tucumán'); 
