<?php

namespace AppBundle\Repository;

/**
 * ConcesionariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcesionariaRepository extends \Doctrine\ORM\EntityRepository
{
}
