<?php

namespace AppBundle\Repository;

/**
 * RegistroDelAutomotorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroDelAutomotorRepository extends \Doctrine\ORM\EntityRepository
{
}
