<?php

namespace AppBundle\Repository;

/**
 * TitularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitularRepository extends \Doctrine\ORM\EntityRepository
{
}
